[tools]
node = "24"

[env]
DB_CONTAINER_NAME = 'reservas_db'
MYSQL_ROOT_PASSWORD = 'root-secret'
MYSQL_DATABASE = 'reservas'
MYSQL_USER = 'user'
MYSQL_PASSWORD = 'reservas-secret'

[tasks.setup]
description = 'Instala dependencias de npm y crea contenedor de MySQL y tabla de fechas'
run = [
    { tasks = ["install", "db:create_table"] },
    { task = "db:create_dates" },
]
