#!/usr/bin/env bash
#MISE description="Create \"asientos\" table in MySQL DB"
#MISE depends = ["db:create_container"]

podman exec -i $DB_CONTAINER_NAME mysql -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE <<EOF
CREATE TABLE asientos (
    asiento INT PRIMARY KEY,
    estado ENUM('Disponible', 'En Proceso', 'Ocupado') NOT NULL DEFAULT 'Disponible'
);
EOF
